// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sre.domain;

import sre.domain.EndLogradouroTipo;

privileged aspect EndLogradouroTipo_Roo_JavaBean {
    
    public Integer EndLogradouroTipo.getVersion() {
        return this.version;
    }
    
    public void EndLogradouroTipo.setVersion(Integer version) {
        this.version = version;
    }
    
}
